parameters:
  lch.menu.validator.class: Lch\MenuBundle\Validator\Constraints\ValidMenuValidator

services:
  lch.menu.form:
    class: Lch\MenuBundle\Form\MenuType
    arguments: [ '@lch.translate.translations_helper', '%jms_i18n_routing.default_locale%' ]
    tags:
      - { name: form.type }

  lch.menu.tree.form:
      class: Lch\MenuBundle\Form\MenuTreeType
      arguments: [ '@doctrine.orm.entity_manager' ]
      tags:
        - { name: form.type }

  lch.menu.location:
      class: Lch\MenuBundle\Form\MenuLocationType
      arguments: [ '%lch.menu.locations%' ]
      tags:
        - { name: form.type }

  lch.menu.twig.extension:
    class: Lch\MenuBundle\Twig\Extension\MenuExtension
    arguments: [ '@doctrine.orm.entity_manager', '%lch.menu.locations%', '%jms_i18n_routing.default_locale%' ]
    tags:
      - { name: twig.extension }
    lazy: true

  lch.menu.validator:
    class: '%lch.menu.validator.class%'
    arguments: ['@doctrine.orm.entity_manager', '@translator' ]
    lazy: true
    tags: { name: validator.constraint_validator}

  lch.menu.tools:
    class: Lch\MenuBundle\Service\MenuTools
    arguments: [ '@doctrine.orm.entity_manager']
#    tags:
#      - { name: twig.extension }
    lazy: true